### PR TITLE
refactor(adapter): Update normailzePath to remove query parameters

### PR DESCRIPTION
**Pull request by folterung**
This is a follow up to issue #35 to get it approved and merged as I need this change made for a project that I am currently working on. Please let me know if I need to do anything else in-order to get this fix merged.

@Dignifiedquire @vojtajina @IgorMinar @btford

### CODE REVIEW

**Comment by folterung** [comment]
I signed it!

**Comment by aik099** [comment]
The messages from @googlebot are really strange. Does it say, that Karma is an Google project now?

**Comment by Dignifiedquire** [comment]
@folterung thanks :octocat: 

@aik099 Karma was more or less always a Google project as @vojtajina was working for Google when he developed it. As I'm the one maintaining it now though (and I do not work for Google) it's not entirely clear anymore. @zzo is looking into some more details on this though.

**Comment by folterung** [comment]
@Dignifiedquire Awesome! Thank you for the quick response. If I can help out with anything just let me know.

**Comment by Dignifiedquire** [comment]
Just pushed a release with this and some cleanups to master. If you want to help please do so, I'm not using requirejs at the moment anymore so it's hard to triage and check things here. If you got any questions feel free to @ mention me and I'll try to answer them the best I can

**Pull request merged**
